=== tcgdex/cards-database/meta/definitions/set.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Serie",
	"description": "Describe a pok√©mon TCG set",
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"id": {
			"description": "set Unique Identifier",
			"type": "string"
		},
		"name": {
			"description": "the name of the set",
			"type": "object",
			"properties": {
				"en": {
					"type": "string"
				},
				"es": {
					"type": "string"
				},
				"pt": {
					"type": "string"
				},
				"fr": {
					"type": "string"
				},
				"it": {
					"type": "string"
				},
				"de": {
					"type": "string"
				}
			}
		},
		"serie": {
			"description": "The serie ID in wich the set is in",
			"type": "string"
		},
		"tcgOnline": {
			"description": "TCG Online ID",
			"type": "string"
		},

		"cardCount": {
			"description": "The number of cards in the set",
			"type": "number"
		},
		"releaseDate": {
			"description": "The date at which the set was released",
			"type": "string"
		}
	},
	"required": [
		"$schema",
		"id",
		"name",
		"serie",
		"cardCount",
		"releaseDate"
	]
}

=== tcgdex/cards-database/data/ex/ex6.json
{
	"$schema": "../../meta/definitions/set.schema.json",
	"cardCount": 112,
	"id": "ex6",
	"name": {
		"de": "EX Feuerrot & Blattgr√ºn",
		"en": "FireRed & LeafGreen",
		"fr": "EX Rouge Feu & Vert Feuille",
		"it": "EX RossoFuoco e VerdeFoglia"
	},
	"releaseDate": "2004-09-01",
	"serie": "ex",
	"tcgOnline": "RG"
}

=== tcgdex/cards-database/data/bw/bw3.json
{
	"$schema": "../../meta/definitions/set.schema.json",
	"cardCount": 101,
	"id": "bw3",
	"name": {
		"de": "Königliche Siege",
		"en": "Noble Victories",
		"es": "Nobles Victorias",
		"fr": "Nobles Victoires",
		"it": "Vittorie Regali",
		"pt": "Vitórias Nobres"
	},
	"releaseDate": "2011-11-16",
	"serie": "bw",
	"tcgOnline": "NVI"
}
