=== tcgdex/cards-database/server/public/v2/card.schema.json
{
	"$ref": "#/definitions/Card",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"Card": {
			"additionalProperties": false,
			"properties": {
				"$schema": {
					"type": "string"
				},
				"abilities": {
					"description": "Pokemon Abilities\n\nmulti abilities ex https://www.tcgdex.net/database/ex/ex15/10",
					"items": {
						"additionalProperties": false,
						"properties": {
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							},
							"type": {
								"enum": [
									"Pokemon Power",
									"Poke-BODY",
									"Poke-POWER",
									"Ability",
									"Ancient Trait"
								],
								"type": "string"
							}
						},
						"required": [
							"effect",
							"name",
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"attacks": {
					"description": "Pokemon Attacks",
					"items": {
						"additionalProperties": false,
						"properties": {
							"cost": {
								"items": {
									"$ref": "#/definitions/Types"
								},
								"type": "array"
							},
							"damage": {
								"type": [
									"string",
									"number"
								]
							},
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							}
						},
						"required": [
							"name"
						],
						"type": "object"
					},
					"type": "array"
				},
				"category": {
					"description": "Card Category\n\n- Pokemon\n- Trainer\n- Energy",
					"enum": [
						"Pokemon",
						"Trainer",
						"Energy"
					],
					"type": "string"
				},
				"description": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Description"
				},
				"dexId": {
					"description": "Pokemon Pokedex ID",
					"items": {
						"type": "number"
					},
					"type": "array"
				},
				"effect": {
					"$ref": "#/definitions/Languages"
				},
				"energyType": {
					"enum": [
						"Normal",
						"Special"
					],
					"type": "string"
				},
				"evolveFrom": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Sub Evolution"
				},
				"hp": {
					"description": "Pokemon HP",
					"type": "number"
				},
				"illustrator": {
					"description": "Card illustrator",
					"type": "string"
				},
				"item": {
					"additionalProperties": false,
					"description": "Pokemon Held Item\n\nex https://www.tcgdex.net/database/dp/dp2/75",
					"properties": {
						"effect": {
							"$ref": "#/definitions/Languages"
						},
						"name": {
							"$ref": "#/definitions/Languages"
						}
					},
					"required": [
						"name",
						"effect"
					],
					"type": "object"
				},
				"level": {
					"description": "Level of the Pokemon\n\nNOTE: can be equal to 'X' when the pokemon is a LEVEL-UP one",
					"type": [
						"number",
						"string"
					]
				},
				"name": {
					"$ref": "#/definitions/Languages",
					"description": "Card Name (Including the suffix if next to card name)"
				},
				"rarity": {
					"description": "Card Rarity\n\n- None https://www.tcgdex.net/database/sm/smp/SM01\n- Common https://www.tcgdex.net/database/xy/xy9/1\n- Uncommon https://www.tcgdex.net/database/xy/xy9/2\n- Rare https://www.tcgdex.net/database/xy/xy9/3\n- Ultra Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/18-Cinderace-V\n- Secret Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/73-Alcremie-VMAX\n- Amazing https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/17-Reshiram",
					"enum": [
						"None",
						"Common",
						"Uncommon",
						"Rare",
						"Ultra Rare",
						"Secret Rare",
						"Amazing"
					],
					"type": "string"
				},
				"regulationMark": {
					"description": "Card regulation Mark\n\nnote: added from Sword & Shield",
					"type": "string"
				},
				"resistances": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"retreat": {
					"type": "number"
				},
				"set": {
					"type": "string",
					"description": "Card Set ID"
				},
				"stage": {
					"description": "Pokemon Stage\n\n- Basic https://www.tcgdex.net/database/xy/xy9/1\n- BREAK https://www.tcgdex.net/database/xy/xy9/18\n- LEVEL-UP https://www.tcgdex.net/database/dp/dp1/121\n- MEGA https://www.tcgdex.net/database/xy/xy1/2\n- RESTORED https://www.tcgdex.net/database/bw/bw5/53\n- Stage1 https://www.tcgdex.net/database/xy/xy9/2\n- Stage2 https://www.tcgdex.net/database/xy/xy9/3\n- VMAX https://www.tcgdex.net/database/swsh/swsh1/50\n- Baby https://www.tcgdex.net/database/swsh/cel25/20A\n- VSTAR https://www.tcgdex.net/database/swsh/swsh9/14",
					"enum": [
						"Basic",
						"BREAK",
						"LEVEL-UP",
						"MEGA",
						"RESTORED",
						"Stage1",
						"Stage2",
						"VMAX",
						"V-UNION",
						"Baby",
						"VSTAR"
					],
					"type": "string"
				},
				"suffix": {
					"description": "Card Suffix\n\n- EX https://www.tcgdex.net/database/ex/ex2/94\n- GX https://www.tcgdex.net/database/sm/sm12/4\n- V https://www.tcgdex.net/database/swsh/swsh1/1\n- Legend https://www.tcgdex.net/database/hgss/hgss1/114\n- Prime https://www.tcgdex.net/database/hgss/hgss2/85\n- SP https://www.tcgdex.net/database/pl/pl1/7\n- TAG TEAM-GX https://www.tcgdex.net/database/sm/sm12/226",
					"enum": [
						"EX",
						"GX",
						"V",
						"Legend",
						"Prime",
						"SP",
						"TAG TEAM-GX"
					],
					"type": "string"
				},
				"trainerType": {
					"enum": [
						"Supporter",
						"Item",
						"Stadium",
						"Tool",
						"Ace Spec",
						"Technical Machine",
						"Goldenrod Game Corner",
						"Rocket's Secret Machine"
					],
					"type": "string"
				},
				"types": {
					"description": "Pokemon Types",
					"items": {
						"$ref": "#/definitions/Types"
					},
					"type": "array"
				},
				"variants": {
					"additionalProperties": false,
					"description": "Card Variants (Override Set Variants)",
					"properties": {
						"firstEdition": {
							"description": "can have a first Edition stamp",
							"type": "boolean"
						},
						"holo": {
							"description": "Holo Card (illustration holographic)",
							"type": "boolean"
						},
						"jumbo": {
							"description": "Can be found in Jumob Format",
							"type": "boolean"
						},
						"normal": {
							"description": "Card base version",
							"type": "boolean"
						},
						"preRelease": {
							"description": "Card has a pre-release stamp",
							"type": "boolean"
						},
						"reverse": {
							"description": "Holo Reverse (colored Background holographic)",
							"type": "boolean"
						},
						"wPromo": {
							"const": true,
							"description": "Card has a W stamp",
							"type": "boolean"
						}
					},
					"type": "object"
				},
				"weaknesses": {
					"description": "Pokemon Weaknesses",
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"weight": {
					"description": "Pokemon Weight",
					"type": "string"
				}
			},
			"required": [
				"name",
				"rarity",
				"category",
				"set"
			],
			"type": "object"
		},
		"Types": {
			"enum": [
				"Colorless",
				"Darkness",
				"Dragon",
				"Fairy",
				"Fighting",
				"Fire",
				"Grass",
				"Lightning",
				"Metal",
				"Psychic",
				"Water"
			],
			"type": "string"
		},
		"Languages": {
			"additionalProperties": false,
			"properties": {
				"de": {
					"type": "string"
				},
				"en": {
					"type": "string"
				},
				"es": {
					"type": "string"
				},
				"fr": {
					"type": "string"
				},
				"it": {
					"type": "string"
				},
				"pt": {
					"type": "string"
				}
			},
			"type": "object"
		}
	}
}

=== tcgdex/cards-database/data/hgss/hgss1/49.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Fire",
				"Colorless"
			],
			"name": {
				"en": "Flare",
				"fr": "Intimidation"
			},
			"damage": 30
		},
		{
			"cost": [
				"Fire",
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Flamethrower",
				"fr": "Lance-flamme"
			},
			"effect": {
				"en": "Discard an Energy attached to Quilava.",
				"fr": "Défaussez-vous d’une carte Énergie attachée à Fleurisson."
			},
			"damage": 60
		}
	],
	"category": "Pokemon",
	"description": {
		"en": "This Pokémon is fully covered by nonflammable fur. It can withstand any kind of fire attack."
	},
	"dexId": [
		156
	],
	"evolveFrom": {
		"en": "Cyndaquil",
		"fr": "Héricendre"
	},
	"hp": 80,
	"illustrator": "Kagemaru Himeno",
	"name": {
		"en": "Quilava",
		"fr": "Fleurisson"
	},
	"rarity": "Uncommon",
	"retreat": 1,
	"set": "hgss1",
	"stage": "Stage1",
	"types": [
		"Fire"
	],
	"variants": {
		"normal": true,
		"reverse": true,
		"holo": false,
		"firstEdition": false
	},
	"weaknesses": [
		{
			"type": "Water",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/sm/sm7/40.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Water",
				"Water",
				"Water",
				"Water"
			],
			"name": {
				"en": "Dwindling Wave",
				"fr": "Vague Faiblissante",
				"es": "Ola Menguante",
				"it": "Onda Evanescente",
				"pt": "Onda Decrescente",
				"de": "Schwindende Welle"
			},
			"effect": {
				"en": "This attack does 40 less damage for each damage counter on this Pokémon.",
				"fr": "Cette attaque inflige 40 dégâts de moins pour chaque marqueur de dégâts placé sur ce Pokémon.",
				"es": "Este ataque hace 40 puntos de daño menos por cada contador de daño en este Pokémon.",
				"it": "Questo attacco infligge 40 danni in meno per ogni segnalino danno presente su questo Pokémon.",
				"pt": "Este ataque causa 40 pontos de dano a menos para cada contador de dano neste Pokémon.",
				"de": "Diese Attacke fügt 40 Schadenspunkte weniger mal der Anzahl der Schadensmarken auf diesem Pokémon zu."
			},
			"damage": "200-"
		}
	],
	"category": "Pokemon",
	"dexId": [
		321
	],
	"evolveFrom": {
		"en": "Wailmer",
		"fr": "Wailmer"
	},
	"hp": 220,
	"illustrator": "Anesaki Dynamic",
	"name": {
		"de": "Wailord",
		"en": "Wailord",
		"es": "Wailord",
		"fr": "Wailord",
		"it": "Wailord",
		"pt": "Wailord"
	},
	"rarity": "Rare",
	"retreat": 4,
	"set": "sm7",
	"stage": "Stage1",
	"types": [
		"Water"
	],
	"weaknesses": [
		{
			"type": "Grass",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Neo/Neo Discovery/39.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Bite",
				"fr": "Morsure"
			},
			"damage": 10
		},
		{
			"cost": [
				"Darkness",
				"Colorless"
			],
			"name": {
				"en": "Plunder",
				"fr": "Pillage"
			},
			"effect": {
				"en": "Before doing damage, discard all Trainer cards attached to the Defending Pokémon.",
				"fr": "Avant d'infliger les dégâts, défaussez toutes les cartes Dresseur attachées au Pokémon Défenseur (avant qu'elles agissent sur les dégâts)."
			},
			"damage": 20
		}
	],
	"category": "Pokemon",
	"description": {
		"fr": "Il utilise différents types d'aboiements pour communiquer avec les autres de son espèce et pour chasser sa proie."
	},
	"dexId": [
		228
	],
	"hp": 40,
	"illustrator": "Shin-ichi Yoshida",
	"name": {
		"en": "Houndour",
		"fr": "Malosse"
	},
	"rarity": "Uncommon",
	"resistances": [
		{
			"type": "Psychic",
			"value": "-30"
		}
	],
	"set": "neo2",
	"stage": "Basic",
	"types": [
		"Darkness"
	]
}

=== tcgdex/cards-database/data/base/base3/56.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"abilities": [
		{
			"type": "Pokemon Power",
			"name": {
				"en": "Cowardice",
				"fr": "Échappée"
			},
			"effect": {
				"en": "At any time during your turn (before your attack), you may return Tentacool to your hand. (Discard all cards attached to Tentacool.) This power can't be used the turn you put Tentacool into play or if Tentacool is Asleep, Confused, or Paralyzed.",
				"fr": "À tout moment pendant votre tour (avant votre attaque), vous pouvez reprendre Tentacool dans votre main. (Défaussez toutes les cartes attachées à Tentacool.) Ce pouvoir ne peut être utilisé dans le tour où vous mettez Tentacool en jeu ou si Tentacool est Endormi, Confus ou Paralysé."
			}
		}
	],
	"attacks": [
		{
			"cost": [
				"Water"
			],
			"name": {
				"en": "Acid",
				"fr": "Urticos"
			},
			"damage": 10
		}
	],
	"category": "Pokemon",
	"description": {
		"fr": "Flottant au bord des côtes, les pêcheurs se font souvent arroser d'acide quand ils en accrochent un."
	},
	"dexId": [
		72
	],
	"hp": 30,
	"illustrator": "Kagemaru Himeno",
	"name": {
		"en": "Tentacool",
		"fr": "Tentacool"
	},
	"rarity": "Common",
	"set": "base3",
	"stage": "Basic",
	"types": [
		"Water"
	],
	"weaknesses": [
		{
			"type": "Lightning",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/swsh/swsh4.5/SV021.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"abilities": [
		{
			"type": "Ability",
			"name": {
				"fr": "Danse Entraînante",
				"en": "Shuffle Dance",
				"es": "Danza Cambio",
				"it": "Mischiadanza",
				"pt": "Balança Esqueleto",
				"de": "Shuffle-Tanz"
			},
			"effect": {
				"fr": "Une fois pendant votre tour, vous pouvez échanger l'une des cartes Récompense de votre adversaire (actuellement face cachée) contre la carte du dessus de son deck. (Les cartes restent face cachée.)",
				"en": "Once during your turn, you may switch 1 of your opponent's face-down Prize cards with the top card of their deck. (The cards stay face down.)",
				"es": "Una vez durante tu turno, puedes cambiar 1 de las cartas de Premio que están boca abajo de tu rival por la primera carta de su baraja. (Las cartas permanecen boca abajo).",
				"it": "Una sola volta durante il tuo turno, puoi scambiare una delle carte Premio coperte del tuo avversario con la prima carta del suo mazzo. Le carte restano coperte.",
				"pt": "Uma vez durante o seu turno, você poderá trocar 1 das cartas de Prêmio viradas para baixo do seu oponente pela carta de cima do baralho dele(a) (as cartas continuam viradas para baixo).",
				"de": "Einmal während deines Zuges kannst du 1 verdeckte Preiskarte deines Gegners gegen die oberste Karte seines Decks austauschen. (Die Karten bleiben verdeckt.)"
			}
		}
	],
	"attacks": [
		{
			"name": {
				"fr": "Folle Aventure",
				"en": "Mad Party",
				"es": "Merienda de Locos",
				"it": "Festa di Matti",
				"pt": "Festa Maluca",
				"de": "Verrückte Party"
			},
			"effect": {
				"fr": "Cette attaque inflige 20 dégâts pour chaque Pokémon dans votre pile de défausse qui a l'attaque Folle Aventure.",
				"en": "This attack does 20 damage for each Pokémon in your discard pile that has the Mad Party attack.",
				"es": "Este ataque hace 20 puntos de daño por cada Pokémon en tu pila de descartes que tenga el ataque Merienda de Locos.",
				"it": "Questo attacco infligge 20 danni per ogni Pokémon nella tua pila degli scarti che ha l'attacco Festa di Matti.",
				"pt": "Este ataque causa 20 pontos de dano para cada Pokémon na sua pilha de descarte que tiver o ataque Festa Maluca.",
				"de": "Diese Attacke fügt für jedes Pokémon in deinem Ablagestapel, das die Attacke Verrückte Party hat, 20 Schadenspunkte zu."
			},
			"damage": "20×",
			"cost": [
				"Water",
				"Colorless",
				"Colorless"
			]
		}
	],
	"category": "Pokemon",
	"description": {
		"en": "It's highly skilled at tap-dancing. It waves its cane of ice in time with its graceful movements."
	},
	"evolveFrom": {
		"fr": "M. Mime de Galar",
		"en": "Galarian Mr. Mime"
	},
	"hp": 120,
	"illustrator": "Hideki Ishikawa",
	"name": {
		"de": "Galar-Pantifrost",
		"en": "Galarian Mr. Rime",
		"es": "Mr. Rime de Galar",
		"fr": "M. Glaquette de Galar",
		"it": "Mr. Rime di Galar",
		"pt": "Mr. Rime de Galar"
	},
	"rarity": "Ultra Rare",
	"regulationMark": "D",
	"retreat": 2,
	"set": "swsh4.5",
	"stage": "Stage1",
	"types": [
		"Water"
	],
	"weaknesses": [
		{
			"type": "Metal",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/xy/xy7/26.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"abilities": [
		{
			"type": "Ability",
			"name": {
				"en": "Electric Effect",
				"fr": "Effet Électrique",
				"es": "Efecto Eléctrico",
				"it": "Elettreffetto",
				"pt": "Efeito Elétrico",
				"de": "Elektro-Effekt"
			},
			"effect": {
				"en": "Each of your Stage 1 Pokémon in play is now a Lightning Pokémon in addition to its existing types.",
				"fr": "Chacun de vos Pokémon de Niveau 1 en jeu est maintenant un Pokémon Lightning en plus de ses types existants.",
				"es": "Cada uno de tus Pokémon de Fase 1 en juego pasa a ser un Pokémon Lightning además de sus tipos actuales.",
				"it": "Ciascuno dei tuoi Pokémon di Fase 1 in gioco diventa di tipo Lightning in aggiunta ai suoi tipi originari.",
				"pt": "Cada um dos seus Pokémon Estágio 1 em jogo é agora um Pokémon Lightning, além dos seus tipos existentes.",
				"de": "Jedes deiner Phase-1-Pokémon im Spiel ist jetzt zusätzlich zu seinen bereits vorhandenen Typen ein Lightning-Pokémon."
			}
		}
	],
	"attacks": [
		{
			"cost": [
				"Lightning",
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Thunder Blast",
				"fr": "Grondement de Tonnerre",
				"es": "Estallido Trueno",
				"it": "Tuonobomba",
				"pt": "Explosão de Trovões",
				"de": "Donnerkeil"
			},
			"effect": {
				"en": "Discard an Energy attached to this Pokémon.",
				"fr": "Défaussez une Énergie attachée à ce Pokémon.",
				"es": "Descarta 1 Energía unida a este Pokémon.",
				"it": "Scarta un'Energia assegnata a questo Pokémon.",
				"pt": "Descarte uma Energia ligada a este Pokémon.",
				"de": "Lege 1 an dieses Pokémon angelegte Energie auf deinen Ablagestapel."
			},
			"damage": 80
		}
	],
	"category": "Pokemon",
	"dexId": [
		135
	],
	"evolveFrom": {
		"en": "Eevee",
		"fr": "Évoli",
		"es": "Eevee",
		"it": "Eevee",
		"pt": "Eevee",
		"de": "Evoli"
	},
	"hp": 90,
	"illustrator": "Sanosuke Sakuma",
	"name": {
		"de": "Blitza",
		"en": "Jolteon",
		"es": "Jolteon",
		"fr": "Voltali",
		"it": "Jolteon",
		"pt": "Jolteon"
	},
	"rarity": "Rare",
	"resistances": [
		{
			"type": "Metal",
			"value": "-20"
		}
	],
	"retreat": 0,
	"set": "xy7",
	"stage": "Stage1",
	"types": [
		"Lightning"
	],
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Sun & Moon/Cosmic Eclipse/153.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Fairy"
			],
			"name": {
				"en": "Cotton Guard",
				"fr": "Cotogarde",
				"es": "Rizo Algodón",
				"it": "Cotonscudo",
				"pt": "Proteção de Algodão",
				"de": "Watteschild"
			},
			"effect": {
				"en": "During your opponent’s next turn, this Pokémon takes 10 less damage from attacks (after applying Weakness and Resistance).",
				"fr": "Pendant le prochain tour de votre adversaire, ce Pokémon subit 10 dégâts de moins provenant des attaques (après application de la Faiblesse et de la Résistance).",
				"es": "Durante el próximo turno de tu rival, los ataques hacen 10 puntos de daño menos a este Pokémon (después de aplicar Debilidad y Resistencia).",
				"it": "Durante il prossimo turno del tuo avversario, questo Pokémon subisce 10 danni in meno dagli attacchi, dopo aver applicato debolezza e resistenza.",
				"pt": "Durante a próxima vez de jogar do seu oponente, este Pokémon receberá 10 pontos de dano a menos de ataques (após a aplicação de Fraqueza e Resistência).",
				"de": "Während des nächsten Zuges deines Gegners werden diesem Pokémon durch Attacken 10 Schadenspunkte weniger zugefügt (nachdem Schwäche und Resistenz verrechnet wurden)."
			},
			"damage": 10
		}
	],
	"category": "Pokemon",
	"dexId": [
		684
	],
	"hp": 60,
	"illustrator": "MAHOU",
	"name": {
		"de": "Flauschling",
		"en": "Swirlix",
		"es": "Swirlix",
		"fr": "Sucroquin",
		"it": "Swirlix",
		"pt": "Swirlix"
	},
	"rarity": "Common",
	"resistances": [
		{
			"type": "Darkness",
			"value": "-20"
		}
	],
	"retreat": 1,
	"set": "sm12",
	"stage": "Basic",
	"types": [
		"Fairy"
	],
	"weaknesses": [
		{
			"type": "Metal",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Sun & Moon/Ultra Prism/10.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Grass"
			],
			"name": {
				"en": "Surprise Attack",
				"fr": "Attaque Surprise",
				"es": "Ataque Sorpresa",
				"it": "Attacco a Sorpresa",
				"pt": "Ataque Surpresa",
				"de": "Überraschungsangriff"
			},
			"effect": {
				"en": "Flip a coin. If tails, this attack does nothing.",
				"fr": "Lancez une pièce. Si c’est pile, cette attaque ne fait rien.",
				"es": "Lanza 1 moneda. Si sale cruz, este ataque no hace nada.",
				"it": "Lancia una moneta. Se esce croce, questo attacco non ha effetto.",
				"pt": "Jogue 1 moeda. Se sair coroa, este ataque não fará nada.",
				"de": "Wirf 1 Münze. Bei Zahl hat diese Attacke keine Auswirkungen."
			},
			"damage": 30
		}
	],
	"category": "Pokemon",
	"dexId": [
		420
	],
	"hp": 50,
	"illustrator": "Asako Ito",
	"name": {
		"de": "Kikugi",
		"en": "Cherubi",
		"es": "Cherubi",
		"fr": "Ceribou",
		"it": "Cherubi",
		"pt": "Cherubi"
	},
	"rarity": "Common",
	"retreat": 1,
	"set": "sm5",
	"stage": "Basic",
	"types": [
		"Grass"
	],
	"weaknesses": [
		{
			"type": "Fire",
			"value": "×2"
		}
	]
}
