=== tcgdex/cards-database/server/public/v2/card.schema.json
{
	"$ref": "#/definitions/Card",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"Card": {
			"additionalProperties": false,
			"properties": {
				"$schema": {
					"type": "string"
				},
				"abilities": {
					"description": "Pokemon Abilities\n\nmulti abilities ex https://www.tcgdex.net/database/ex/ex15/10",
					"items": {
						"additionalProperties": false,
						"properties": {
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							},
							"type": {
								"enum": [
									"Pokemon Power",
									"Poke-BODY",
									"Poke-POWER",
									"Ability",
									"Ancient Trait"
								],
								"type": "string"
							}
						},
						"required": [
							"effect",
							"name",
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"attacks": {
					"description": "Pokemon Attacks",
					"items": {
						"additionalProperties": false,
						"properties": {
							"cost": {
								"items": {
									"$ref": "#/definitions/Types"
								},
								"type": "array"
							},
							"damage": {
								"type": [
									"string",
									"number"
								]
							},
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							}
						},
						"required": [
							"name"
						],
						"type": "object"
					},
					"type": "array"
				},
				"category": {
					"description": "Card Category\n\n- Pokemon\n- Trainer\n- Energy",
					"enum": [
						"Pokemon",
						"Trainer",
						"Energy"
					],
					"type": "string"
				},
				"description": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Description"
				},
				"dexId": {
					"description": "Pokemon Pokedex ID",
					"items": {
						"type": "number"
					},
					"type": "array"
				},
				"effect": {
					"$ref": "#/definitions/Languages"
				},
				"energyType": {
					"enum": [
						"Normal",
						"Special"
					],
					"type": "string"
				},
				"evolveFrom": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Sub Evolution"
				},
				"hp": {
					"description": "Pokemon HP",
					"type": "number"
				},
				"illustrator": {
					"description": "Card illustrator",
					"type": "string"
				},
				"item": {
					"additionalProperties": false,
					"description": "Pokemon Held Item\n\nex https://www.tcgdex.net/database/dp/dp2/75",
					"properties": {
						"effect": {
							"$ref": "#/definitions/Languages"
						},
						"name": {
							"$ref": "#/definitions/Languages"
						}
					},
					"required": [
						"name",
						"effect"
					],
					"type": "object"
				},
				"level": {
					"description": "Level of the Pokemon\n\nNOTE: can be equal to 'X' when the pokemon is a LEVEL-UP one",
					"type": [
						"number",
						"string"
					]
				},
				"name": {
					"$ref": "#/definitions/Languages",
					"description": "Card Name (Including the suffix if next to card name)"
				},
				"rarity": {
					"description": "Card Rarity\n\n- None https://www.tcgdex.net/database/sm/smp/SM01\n- Common https://www.tcgdex.net/database/xy/xy9/1\n- Uncommon https://www.tcgdex.net/database/xy/xy9/2\n- Rare https://www.tcgdex.net/database/xy/xy9/3\n- Ultra Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/18-Cinderace-V\n- Secret Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/73-Alcremie-VMAX\n- Amazing https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/17-Reshiram",
					"enum": [
						"None",
						"Common",
						"Uncommon",
						"Rare",
						"Ultra Rare",
						"Secret Rare",
						"Amazing"
					],
					"type": "string"
				},
				"regulationMark": {
					"description": "Card regulation Mark\n\nnote: added from Sword & Shield",
					"type": "string"
				},
				"resistances": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"retreat": {
					"type": "number"
				},
				"set": {
					"type": "string",
					"description": "Card Set ID"
				},
				"stage": {
					"description": "Pokemon Stage\n\n- Basic https://www.tcgdex.net/database/xy/xy9/1\n- BREAK https://www.tcgdex.net/database/xy/xy9/18\n- LEVEL-UP https://www.tcgdex.net/database/dp/dp1/121\n- MEGA https://www.tcgdex.net/database/xy/xy1/2\n- RESTORED https://www.tcgdex.net/database/bw/bw5/53\n- Stage1 https://www.tcgdex.net/database/xy/xy9/2\n- Stage2 https://www.tcgdex.net/database/xy/xy9/3\n- VMAX https://www.tcgdex.net/database/swsh/swsh1/50\n- Baby https://www.tcgdex.net/database/swsh/cel25/20A\n- VSTAR https://www.tcgdex.net/database/swsh/swsh9/14",
					"enum": [
						"Basic",
						"BREAK",
						"LEVEL-UP",
						"MEGA",
						"RESTORED",
						"Stage1",
						"Stage2",
						"VMAX",
						"V-UNION",
						"Baby",
						"VSTAR"
					],
					"type": "string"
				},
				"suffix": {
					"description": "Card Suffix\n\n- EX https://www.tcgdex.net/database/ex/ex2/94\n- GX https://www.tcgdex.net/database/sm/sm12/4\n- V https://www.tcgdex.net/database/swsh/swsh1/1\n- Legend https://www.tcgdex.net/database/hgss/hgss1/114\n- Prime https://www.tcgdex.net/database/hgss/hgss2/85\n- SP https://www.tcgdex.net/database/pl/pl1/7\n- TAG TEAM-GX https://www.tcgdex.net/database/sm/sm12/226",
					"enum": [
						"EX",
						"GX",
						"V",
						"Legend",
						"Prime",
						"SP",
						"TAG TEAM-GX"
					],
					"type": "string"
				},
				"trainerType": {
					"enum": [
						"Supporter",
						"Item",
						"Stadium",
						"Tool",
						"Ace Spec",
						"Technical Machine",
						"Goldenrod Game Corner",
						"Rocket's Secret Machine"
					],
					"type": "string"
				},
				"types": {
					"description": "Pokemon Types",
					"items": {
						"$ref": "#/definitions/Types"
					},
					"type": "array"
				},
				"variants": {
					"additionalProperties": false,
					"description": "Card Variants (Override Set Variants)",
					"properties": {
						"firstEdition": {
							"description": "can have a first Edition stamp",
							"type": "boolean"
						},
						"holo": {
							"description": "Holo Card (illustration holographic)",
							"type": "boolean"
						},
						"jumbo": {
							"description": "Can be found in Jumob Format",
							"type": "boolean"
						},
						"normal": {
							"description": "Card base version",
							"type": "boolean"
						},
						"preRelease": {
							"description": "Card has a pre-release stamp",
							"type": "boolean"
						},
						"reverse": {
							"description": "Holo Reverse (colored Background holographic)",
							"type": "boolean"
						},
						"wPromo": {
							"const": true,
							"description": "Card has a W stamp",
							"type": "boolean"
						}
					},
					"type": "object"
				},
				"weaknesses": {
					"description": "Pokemon Weaknesses",
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"weight": {
					"description": "Pokemon Weight",
					"type": "string"
				}
			},
			"required": [
				"name",
				"rarity",
				"category",
				"set"
			],
			"type": "object"
		},
		"Types": {
			"enum": [
				"Colorless",
				"Darkness",
				"Dragon",
				"Fairy",
				"Fighting",
				"Fire",
				"Grass",
				"Lightning",
				"Metal",
				"Psychic",
				"Water"
			],
			"type": "string"
		},
		"Languages": {
			"additionalProperties": false,
			"properties": {
				"de": {
					"type": "string"
				},
				"en": {
					"type": "string"
				},
				"es": {
					"type": "string"
				},
				"fr": {
					"type": "string"
				},
				"it": {
					"type": "string"
				},
				"pt": {
					"type": "string"
				}
			},
			"type": "object"
		}
	}
}

=== tcgdex/cards-database/data/EX/Ruby & Sapphire/65.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Darkness"
			],
			"name": {
				"en": "Shadow Bind",
				"fr": "Étreinte d'ombre"
			},
			"effect": {
				"en": "The Defending Pokémon can't retreat until the end of your opponent's next turn.",
				"fr": "Le Pokémon Défenseur ne peut pas battre en retraite tant que le prochain tour de votre adversaire n'est pas terminé."
			},
			"damage": 10
		}
	],
	"category": "Pokemon",
	"dexId": [
		261
	],
	"hp": 50,
	"illustrator": "Naoyo Kimura",
	"name": {
		"en": "Poochyena",
		"fr": "Medhyena"
	},
	"rarity": "Common",
	"resistances": [
		{
			"type": "Psychic",
			"value": "-30"
		}
	],
	"set": "ex1",
	"stage": "Basic",
	"types": [
		"Darkness"
	],
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/swsh/swsh5/77.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"name": {
				"en": "Pound",
				"fr": "Écras'Face",
				"es": "Destructor",
				"it": "Botta",
				"pt": "Pancada",
				"de": "Klaps"
			},
			"damage": 20,
			"cost": [
				"Colorless"
			]
		},
		{
			"name": {
				"en": "Spinning Whip",
				"fr": "Fouet Tournant",
				"es": "Látigo Giratorio",
				"it": "Frustata Rotante",
				"pt": "Chicote Giratório",
				"de": "Wirbelpeitsche"
			},
			"effect": {
				"en": "Your opponent's Active Pokémon is now Confused. Shuffle this Pokémon and all attached cards into your deck.",
				"fr": "Le Pokémon Actif de votre adversaire est maintenant Confus. Mélangez dans votre deck ce Pokémon et toutes les cartes attachées.",
				"es": "El Pokémon Activo de tu rival pasa a estar Confundido. Pon este Pokémon y todas las cartas unidas a él en tu baraja, y baraja todas las cartas.",
				"it": "Il Pokémon attivo del tuo avversario viene confuso. Rimischia questo Pokémon e tutte le carte a esso assegnate nel tuo mazzo.",
				"pt": "O Pokémon Ativo do seu oponente agora está Confuso. Embaralhe este Pokémon e todas as cartas ligadas a ele no seu baralho.",
				"de": "Das Aktive Pokémon deines Gegners ist jetzt verwirrt. Mische dieses Pokémon und alle angelegten Karten in dein Deck."
			},
			"damage": 90,
			"cost": [
				"Fighting",
				"Colorless"
			]
		}
	],
	"category": "Pokemon",
	"description": {
		"en": "When Mienshao lets out a bizarre wail, you're in danger. A flurry of kicks and chops too fast to see is about to be unleashed!"
	},
	"evolveFrom": {
		"en": "Mienfoo",
		"fr": "Kungfouine",
		"es": "Mienfoo",
		"it": "Mienfoo",
		"pt": "Mienfoo",
		"de": "Lin-Fu"
	},
	"hp": 90,
	"illustrator": "Taira Akitsu",
	"name": {
		"de": "Wie-Shu",
		"en": "Mienshao",
		"es": "Mienshao",
		"fr": "Shaofouine",
		"it": "Mienshao",
		"pt": "Mienshao"
	},
	"rarity": "Rare",
	"regulationMark": "E",
	"retreat": 1,
	"set": "swsh5",
	"stage": "Stage1",
	"types": [
		"Fighting"
	],
	"variants": {
		"normal": true,
		"reverse": true,
		"holo": false,
		"firstEdition": false
	},
	"weaknesses": [
		{
			"type": "Psychic",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Sun & Moon/Celestial Storm/23.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Magma Ring",
				"fr": "Anneau Magma",
				"es": "Anillo de Magma",
				"it": "Anello di Magma",
				"pt": "Anel de Magma",
				"de": "Magmaring"
			},
			"effect": {
				"en": "The Defending Pokémon can’t retreat during your opponent’s next turn.",
				"fr": "Le Pokémon Défenseur ne peut pas battre en retraite pendant le prochain tour de votre adversaire.",
				"es": "El Pokémon Defensor no puede retirarse durante el próximo turno de tu rival.",
				"it": "Durante il prossimo turno del tuo avversario, il Pokémon difensore non può ritirarsi.",
				"pt": "O Pokémon Defensor não poderá recuar durante a próxima vez de jogar do seu oponente.",
				"de": "Das Verteidigende Pokémon kann sich während des nächsten Zuges deines Gegners nicht zurückziehen."
			},
			"damage": 10
		},
		{
			"cost": [
				"Fire",
				"Colorless"
			],
			"name": {
				"en": "Flare",
				"fr": "Intimidation",
				"es": "Llama",
				"it": "Fiammata",
				"pt": "Labareda",
				"de": "Flackern"
			},
			"damage": 20
		}
	],
	"category": "Pokemon",
	"dexId": [
		218
	],
	"hp": 70,
	"illustrator": "Midori Harada",
	"name": {
		"de": "Schneckmag",
		"en": "Slugma",
		"es": "Slugma",
		"fr": "Limagma",
		"it": "Slugma",
		"pt": "Slugma"
	},
	"rarity": "Common",
	"retreat": 2,
	"set": "sm7",
	"stage": "Basic",
	"types": [
		"Fire"
	],
	"weaknesses": [
		{
			"type": "Water",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/ex/ex4/69.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"category": "Trainer",
	"effect": {
		"fr": "Vous ne pouvez jouer qu'une seule carte Supporter par tour. Lorsque vous jouez cette carte, placez-la à côté de votre Pokémon Actif. À la fin de votre tour, défaussez-la.\n\nDéfaussez 1 Pokémon de votre main. Ensuite, piochez 3 cartes. Si vous avez défaussé un Pokémon dont le nom comporte Team Aqua, piochez 4 cartes."
	},
	"illustrator": "Ken Sugimori",
	"name": {
		"en": "Team Aqua Schemer",
		"fr": "Manipulateur de Team Aqua"
	},
	"rarity": "Common",
	"set": "ex4",
	"trainerType": "Supporter"
}

=== tcgdex/cards-database/data/Sun & Moon/Burning Shadows/127.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"category": "Trainer",
	"effect": {
		"fr": "Chaque joueur compte les cartes qu’il a en main, les mélange dans son deck, puis pioche ce même nombre de cartes.",
		"en": "Each player counts the cards in their hand, shuffles those cards into their deck, then draws that many cards.",
		"es": "Cada jugador cuenta las cartas de su mano, pone esas cartas en su baraja y las baraja todas, y después roba ese mismo número de cartas.",
		"it": "Ciascun giocatore conta le carte che ha in mano, le rimischia nel proprio mazzo, quindi pesca lo stesso numero di carte.",
		"pt": "Cada jogador conta as cartas nas próprias mãos, embaralha-as no próprio baralho e em seguida compra aquele mesmo número de cartas.",
		"de": "Jeder Spieler zählt die Karten auf seiner Hand, mischt jene Karten in sein Deck und zieht anschließend dieselbe Anzahl Karten."
	},
	"illustrator": "take",
	"name": {
		"de": "Pia",
		"en": "Wicke",
		"es": "Zyra",
		"fr": "Vicky",
		"it": "Ciceria",
		"pt": "Lara"
	},
	"rarity": "Uncommon",
	"set": "sm3",
	"trainerType": "Supporter"
}

=== tcgdex/cards-database/data/Black & White/Dark Explorers/41.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Ram"
			},
			"damage": 10
		},
		{
			"cost": [
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Bug Bite"
			},
			"damage": 20
		}
	],
	"category": "Pokemon",
	"dexId": [
		595
	],
	"hp": 30,
	"illustrator": "MAHOU",
	"name": {
		"de": "Wattzapf",
		"en": "Joltik",
		"es": "Joltik",
		"fr": "Statitik",
		"it": "Joltik",
		"pt": "Joltik"
	},
	"rarity": "Common",
	"retreat": 1,
	"set": "bw5",
	"stage": "Basic",
	"types": [
		"Lightning"
	],
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "Ã—2"
		}
	]
}

=== tcgdex/cards-database/data/Diamond & Pearl/Majestic Dawn/63.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"name": {
				"en": "Gnaw",
				"fr": "Rogne"
			},
			"damage": 10
		},
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Sand Attack",
				"fr": "Jet de sable"
			},
			"effect": {
				"en": "If the Defending Pokémon tries to attack during your opponent's next turn, your opponent flips a coin. If tails, that attack does nothing.",
				"fr": "Si le Pokémon Défenseur essaye d'attaquer lors du prochain tour de votre adversaire, celui-ci lance une pièce. Si c'est pile, cette attaque est sans effet."
			}
		}
	],
	"category": "Pokemon",
	"dexId": [
		133
	],
	"hp": 60,
	"illustrator": "Kagemaru Himeno",
	"name": {
		"en": "Eevee",
		"fr": "Evoli"
	},
	"rarity": "Common",
	"retreat": 1,
	"set": "dp5",
	"stage": "Basic",
	"types": [
		"Colorless"
	],
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "+10"
		}
	]
}

=== tcgdex/cards-database/data/bw/dv1/13.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Fighting",
				"Metal"
			],
			"name": {
				"en": "Lunge",
				"fr": "Coup Rapide"
			},
			"effect": {
				"en": "Flip a coin. If tails, this attack does nothing.",
				"fr": "Lancez une pièce. Si c'est pile, cette attaque ne fait rien."
			},
			"damage": 30
		}
	],
	"category": "Pokemon",
	"dexId": [
		610
	],
	"hp": 50,
	"illustrator": "TOKIYA",
	"name": {
		"en": "Axew",
		"fr": "Coupenotte"
	},
	"rarity": "Rare",
	"retreat": 1,
	"set": "dv1",
	"stage": "Basic",
	"types": [
		"Dragon"
	],
	"weaknesses": [
		{
			"type": "Dragon",
			"value": "×2"
		}
	]
}
