=== tcgdex/cards-database/server/public/v2/card.schema.json
{
	"$ref": "#/definitions/Card",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"Card": {
			"additionalProperties": false,
			"properties": {
				"$schema": {
					"type": "string"
				},
				"abilities": {
					"description": "Pokemon Abilities\n\nmulti abilities ex https://www.tcgdex.net/database/ex/ex15/10",
					"items": {
						"additionalProperties": false,
						"properties": {
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							},
							"type": {
								"enum": [
									"Pokemon Power",
									"Poke-BODY",
									"Poke-POWER",
									"Ability",
									"Ancient Trait"
								],
								"type": "string"
							}
						},
						"required": [
							"effect",
							"name",
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"attacks": {
					"description": "Pokemon Attacks",
					"items": {
						"additionalProperties": false,
						"properties": {
							"cost": {
								"items": {
									"$ref": "#/definitions/Types"
								},
								"type": "array"
							},
							"damage": {
								"type": [
									"string",
									"number"
								]
							},
							"effect": {
								"$ref": "#/definitions/Languages"
							},
							"name": {
								"$ref": "#/definitions/Languages"
							}
						},
						"required": [
							"name"
						],
						"type": "object"
					},
					"type": "array"
				},
				"category": {
					"description": "Card Category\n\n- Pokemon\n- Trainer\n- Energy",
					"enum": [
						"Pokemon",
						"Trainer",
						"Energy"
					],
					"type": "string"
				},
				"description": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Description"
				},
				"dexId": {
					"description": "Pokemon Pokedex ID",
					"items": {
						"type": "number"
					},
					"type": "array"
				},
				"effect": {
					"$ref": "#/definitions/Languages"
				},
				"energyType": {
					"enum": [
						"Normal",
						"Special"
					],
					"type": "string"
				},
				"evolveFrom": {
					"$ref": "#/definitions/Languages",
					"description": "Pokemon Sub Evolution"
				},
				"hp": {
					"description": "Pokemon HP",
					"type": "number"
				},
				"illustrator": {
					"description": "Card illustrator",
					"type": "string"
				},
				"item": {
					"additionalProperties": false,
					"description": "Pokemon Held Item\n\nex https://www.tcgdex.net/database/dp/dp2/75",
					"properties": {
						"effect": {
							"$ref": "#/definitions/Languages"
						},
						"name": {
							"$ref": "#/definitions/Languages"
						}
					},
					"required": [
						"name",
						"effect"
					],
					"type": "object"
				},
				"level": {
					"description": "Level of the Pokemon\n\nNOTE: can be equal to 'X' when the pokemon is a LEVEL-UP one",
					"type": [
						"number",
						"string"
					]
				},
				"name": {
					"$ref": "#/definitions/Languages",
					"description": "Card Name (Including the suffix if next to card name)"
				},
				"rarity": {
					"description": "Card Rarity\n\n- None https://www.tcgdex.net/database/sm/smp/SM01\n- Common https://www.tcgdex.net/database/xy/xy9/1\n- Uncommon https://www.tcgdex.net/database/xy/xy9/2\n- Rare https://www.tcgdex.net/database/xy/xy9/3\n- Ultra Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/18-Cinderace-V\n- Secret Rare https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/73-Alcremie-VMAX\n- Amazing https://www.tcgdex.net/database/Sword-&-Shield/Shining-Fates/17-Reshiram",
					"enum": [
						"None",
						"Common",
						"Uncommon",
						"Rare",
						"Ultra Rare",
						"Secret Rare",
						"Amazing"
					],
					"type": "string"
				},
				"regulationMark": {
					"description": "Card regulation Mark\n\nnote: added from Sword & Shield",
					"type": "string"
				},
				"resistances": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"retreat": {
					"type": "number"
				},
				"set": {
					"type": "string",
					"description": "Card Set ID"
				},
				"stage": {
					"description": "Pokemon Stage\n\n- Basic https://www.tcgdex.net/database/xy/xy9/1\n- BREAK https://www.tcgdex.net/database/xy/xy9/18\n- LEVEL-UP https://www.tcgdex.net/database/dp/dp1/121\n- MEGA https://www.tcgdex.net/database/xy/xy1/2\n- RESTORED https://www.tcgdex.net/database/bw/bw5/53\n- Stage1 https://www.tcgdex.net/database/xy/xy9/2\n- Stage2 https://www.tcgdex.net/database/xy/xy9/3\n- VMAX https://www.tcgdex.net/database/swsh/swsh1/50\n- Baby https://www.tcgdex.net/database/swsh/cel25/20A\n- VSTAR https://www.tcgdex.net/database/swsh/swsh9/14",
					"enum": [
						"Basic",
						"BREAK",
						"LEVEL-UP",
						"MEGA",
						"RESTORED",
						"Stage1",
						"Stage2",
						"VMAX",
						"V-UNION",
						"Baby",
						"VSTAR"
					],
					"type": "string"
				},
				"suffix": {
					"description": "Card Suffix\n\n- EX https://www.tcgdex.net/database/ex/ex2/94\n- GX https://www.tcgdex.net/database/sm/sm12/4\n- V https://www.tcgdex.net/database/swsh/swsh1/1\n- Legend https://www.tcgdex.net/database/hgss/hgss1/114\n- Prime https://www.tcgdex.net/database/hgss/hgss2/85\n- SP https://www.tcgdex.net/database/pl/pl1/7\n- TAG TEAM-GX https://www.tcgdex.net/database/sm/sm12/226",
					"enum": [
						"EX",
						"GX",
						"V",
						"Legend",
						"Prime",
						"SP",
						"TAG TEAM-GX"
					],
					"type": "string"
				},
				"trainerType": {
					"enum": [
						"Supporter",
						"Item",
						"Stadium",
						"Tool",
						"Ace Spec",
						"Technical Machine",
						"Goldenrod Game Corner",
						"Rocket's Secret Machine"
					],
					"type": "string"
				},
				"types": {
					"description": "Pokemon Types",
					"items": {
						"$ref": "#/definitions/Types"
					},
					"type": "array"
				},
				"variants": {
					"additionalProperties": false,
					"description": "Card Variants (Override Set Variants)",
					"properties": {
						"firstEdition": {
							"description": "can have a first Edition stamp",
							"type": "boolean"
						},
						"holo": {
							"description": "Holo Card (illustration holographic)",
							"type": "boolean"
						},
						"jumbo": {
							"description": "Can be found in Jumob Format",
							"type": "boolean"
						},
						"normal": {
							"description": "Card base version",
							"type": "boolean"
						},
						"preRelease": {
							"description": "Card has a pre-release stamp",
							"type": "boolean"
						},
						"reverse": {
							"description": "Holo Reverse (colored Background holographic)",
							"type": "boolean"
						},
						"wPromo": {
							"const": true,
							"description": "Card has a W stamp",
							"type": "boolean"
						}
					},
					"type": "object"
				},
				"weaknesses": {
					"description": "Pokemon Weaknesses",
					"items": {
						"additionalProperties": false,
						"properties": {
							"type": {
								"$ref": "#/definitions/Types"
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"type"
						],
						"type": "object"
					},
					"type": "array"
				},
				"weight": {
					"description": "Pokemon Weight",
					"type": "string"
				}
			},
			"required": [
				"name",
				"rarity",
				"category",
				"set"
			],
			"type": "object"
		},
		"Types": {
			"enum": [
				"Colorless",
				"Darkness",
				"Dragon",
				"Fairy",
				"Fighting",
				"Fire",
				"Grass",
				"Lightning",
				"Metal",
				"Psychic",
				"Water"
			],
			"type": "string"
		},
		"Languages": {
			"additionalProperties": false,
			"properties": {
				"de": {
					"type": "string"
				},
				"en": {
					"type": "string"
				},
				"es": {
					"type": "string"
				},
				"fr": {
					"type": "string"
				},
				"it": {
					"type": "string"
				},
				"pt": {
					"type": "string"
				}
			},
			"type": "object"
		}
	}
}

=== tcgdex/cards-database/data/neo/neo1/8.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Water",
				"Water",
				"Colorless"
			],
			"name": {
				"en": "Agility",
				"fr": "Hâte"
			},
			"effect": {
				"en": "Flip a coin. If heads, during your opponent's next turn, prevent all effects of attacks, including damage, done to Kingdra.",
				"fr": "Lancez une pièce. Si c'est face, pendant le prochain tour de votre adversaire, prévenez tous les effets d'attaques, y compris les dégâts, infligés à Hyporoi."
			},
			"damage": 30
		},
		{
			"cost": [
				"Water",
				"Water",
				"Water",
				"Water"
			],
			"name": {
				"en": "Dragon Tornado",
				"fr": "Tornade du dragon"
			},
			"effect": {
				"en": "If this attack doesn't Knock Out the Defending Pokémon, and if there are any Pokémon on your opponent's Bench, choose 1 of them and switch it with the Defending Pokémon.",
				"fr": "Si cette attaque ne met pas K.O. le Pokémon Défenseur, et s'il y a des Pokémon sur le Banc de votre adversaire, choisissez l'un d'eux et échangez-le avec le Pokémon Défenseur"
			},
			"damage": 50
		}
	],
	"category": "Pokemon",
	"description": {
		"fr": "On prétend qu'il se cache dans des grottes sous-marines. Il peut créer des tourbillons rien que par son bâillement."
	},
	"dexId": [
		230
	],
	"evolveFrom": {
		"en": "Seadra"
	},
	"hp": 90,
	"illustrator": "Ken Sugimori",
	"name": {
		"en": "Kingdra",
		"fr": "Hyporoi"
	},
	"rarity": "Rare",
	"set": "neo1",
	"stage": "Stage2",
	"types": [
		"Water"
	]
}

=== tcgdex/cards-database/data/Black & White/Plasma Storm/111.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Collect",
				"fr": "Collecte"
			},
			"effect": {
				"en": "Draw a card.",
				"fr": "Piochez une carte."
			}
		},
		{
			"cost": [
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Slam",
				"fr": "Souplesse"
			},
			"effect": {
				"en": "Flip 2 coins. This attack does 20 damage times the number of heads.",
				"fr": "Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face."
			},
			"damage": 20
		}
	],
	"category": "Pokemon",
	"dexId": [
		504
	],
	"hp": 50,
	"illustrator": "Naoki Saito",
	"name": {
		"de": "Nagelotz",
		"en": "Patrat",
		"es": "Patrat",
		"fr": "Ratentif",
		"it": "Patrat",
		"pt": "Patrat"
	},
	"rarity": "Common",
	"retreat": 1,
	"set": "bw8",
	"stage": "Basic",
	"types": [
		"Colorless"
	],
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Black & White/Dragons Exalted/63.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Spinning Attack",
				"fr": "Attaque Tournante"
			},
			"damage": 10
		},
		{
			"cost": [
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Reverse Spin",
				"fr": "Vrille Renversante"
			},
			"effect": {
				"en": "Your opponent shuffles his or her hand into his or her deck and draws 4 cards.",
				"fr": "Votre adversaire mélange sa main avec son deck et pioche 4 cartes."
			}
		}
	],
	"category": "Pokemon",
	"dexId": [
		343
	],
	"hp": 60,
	"illustrator": "Shigenori Negishi",
	"name": {
		"de": "Puppance",
		"en": "Baltoy",
		"es": "Baltoy",
		"fr": "Balbuto",
		"it": "Baltoy",
		"pt": "Baltoy"
	},
	"rarity": "Common",
	"retreat": 1,
	"set": "bw6",
	"stage": "Basic",
	"types": [
		"Fighting"
	],
	"weaknesses": [
		{
			"type": "Grass",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/EX/Legend Maker/71.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"abilities": [
		{
			"type": "Poke-POWER",
			"name": {
				"en": "Baby Evolution",
				"fr": "Évolution bébé"
			},
			"effect": {
				"en": "Once during your turn (before your attack), you may put Wobbuffet from your hand onto Wynaut (this counts as evolving Wynaut) and remove all damage counters from Wynaut.",
				"fr": "Une seule fois lors de votre tour (avant votre attaque), vous pouvez placer Qulbutoké de votre main sur Okéoké (vous le faites ainsi évoluer) et retirer à Okéoké tous ses marqueurs de dégât."
			}
		}
	],
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Confusion Wave",
				"fr": "Vague de confusion"
			},
			"effect": {
				"en": "Both Wynaut and the Defending Pokémon are now Confused.",
				"fr": "Okéoké et le Pokémon Défenseur sont maintenant Confus."
			}
		}
	],
	"category": "Pokemon",
	"dexId": [
		360
	],
	"hp": 50,
	"illustrator": "Yuka Morii",
	"name": {
		"en": "Wynaut",
		"fr": "Okéoké"
	},
	"rarity": "Common",
	"set": "ex12",
	"stage": "Basic",
	"types": [
		"Psychic"
	],
	"weaknesses": [
		{
			"type": "Psychic",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/E-Card/Expedition Base Set/150.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"category": "Trainer",
	"effect": {
		"fr": "Attachez Fétiche de force à un de vos Pokémon qui n'a pas d'Outil Pokémon attaché à lui.\n\nÀ chaque fois qu'une attaque du Pokémon sur lequel est attachée Fétiche de force inflige des dégâts (après application de la Faiblesse et de la Résistance), cette attaque inflige 10 dégâts supplémentaires. À la fin de votre tour où cet effet a lieu, défaussez-vous de Fétiche de force."
	},
	"illustrator": "Keiji Kinebuchi",
	"name": {
		"en": "Strength Charm",
		"fr": "Fétiche de force"
	},
	"rarity": "Uncommon",
	"set": "ecard1"
}

=== tcgdex/cards-database/data/hgss/hgss4/33.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Colorless"
			],
			"name": {
				"en": "Light Punch",
				"fr": "Poing léger"
			},
			"damage": 10
		},
		{
			"cost": [
				"Lightning",
				"Lightning",
				"Colorless"
			],
			"name": {
				"en": "Shock Bolt",
				"fr": "Choc’éclair"
			},
			"effect": {
				"en": "Flip a coin. If tails, discard all Lightning Energy attached to Electabuzz.",
				"fr": "Lancez une pièce. Si c’est pile, défaussez toutes les cartes Énergie Lightning attachées à Elektek."
			},
			"damage": 60
		}
	],
	"category": "Pokemon",
	"description": {
		"en": "Its body constantly discharges electricity. Getting close to it will make your hair stand on end."
	},
	"dexId": [
		125
	],
	"hp": 70,
	"illustrator": "TOKIYA",
	"name": {
		"en": "Electabuzz",
		"fr": "Elektek"
	},
	"rarity": "Uncommon",
	"resistances": [
		{
			"type": "Metal",
			"value": "-20"
		}
	],
	"retreat": 2,
	"set": "hgss4",
	"stage": "Basic",
	"types": [
		"Lightning"
	],
	"variants": {
		"normal": true,
		"reverse": true,
		"holo": false,
		"firstEdition": false
	},
	"weaknesses": [
		{
			"type": "Fighting",
			"value": "×2"
		}
	]
}

=== tcgdex/cards-database/data/Sun & Moon/Sun & Moon/123.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"category": "Trainer",
	"effect": {
		"fr": "Cherchez un Pokémon de base dans votre deck et placez-le sur votre Banc. Mélangez ensuite votre deck.",
		"en": "Search your deck for a Basic Pokémon and put it onto your Bench. Then, shuffle your deck.",
		"es": "Busca en tu baraja 1 Pokémon Básico y ponlo en tu Banca. Después, baraja las cartas de tu baraja.",
		"it": "Cerca nel tuo mazzo un Pokémon Base e mettilo nella tua panchina. Poi rimischia le carte del tuo mazzo.",
		"pt": "Procure por 1 Pokémon Básico no seu baralho e coloque-o no seu Banco. Em seguida, embaralhe o seu baralho.",
		"de": "Durchsuche dein Deck nach 1 Basis-Pokémon und lege es auf deine Bank. Mische anschließend dein Deck."
	},
	"illustrator": "Toyste Beach",
	"name": {
		"de": "Nestball",
		"en": "Nest Ball",
		"es": "Nido Ball",
		"fr": "Faiblo Ball",
		"it": "Minor Ball",
		"pt": "Bola de Ninho"
	},
	"rarity": "Uncommon",
	"set": "sm1",
	"trainerType": "Item"
}

=== tcgdex/cards-database/data/Diamond & Pearl/Stormfront/46.json
{
	"$schema": "../../../meta/definitions/card.schema.json",
	"attacks": [
		{
			"cost": [
				"Fighting",
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Rouse",
				"fr": "Éveiller"
			},
			"effect": {
				"en": "Does 20 damage plus 10 more damage for each damage counter on Piloswine. Then, remove 4 damage counters from Piloswine.",
				"fr": "Inflige 20 dégâts plus 10 dégâts supplémentaires pour chaque marqueur de dégât sur Cochignon. Ensuite, retirez à Cochignon 4 marqueurs de dégât."
			},
			"damage": "20+"
		},
		{
			"cost": [
				"Fighting",
				"Colorless",
				"Colorless",
				"Colorless"
			],
			"name": {
				"en": "Overrun",
				"fr": "Dépassement"
			},
			"effect": {
				"en": "Does 20 damage to 1 of your opponent's Benched Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)",
				"fr": "Inflige 20 dégâts à 1 des Pokémon de Banc de votre adversaire. (Vous ne pouvez pas appliquer la Faiblesse et la Résistance aux Pokémon de Banc.)"
			},
			"damage": 60
		}
	],
	"category": "Pokemon",
	"description": {
		"fr": "Il ne voit rien à cause de sa fourrure touffue et se repère à l'aide de son nez délicat."
	},
	"dexId": [
		221
	],
	"evolveFrom": {
		"en": "Swinub",
		"fr": "Marcacrin"
	},
	"hp": 90,
	"illustrator": "Mitsuhiro Arita",
	"name": {
		"en": "Piloswine",
		"fr": "Cochignon"
	},
	"rarity": "Uncommon",
	"resistances": [
		{
			"type": "Lightning",
			"value": "-20"
		}
	],
	"retreat": 2,
	"set": "dp7",
	"stage": "Stage1",
	"types": [
		"Fighting"
	],
	"weaknesses": [
		{
			"type": "Grass",
			"value": "+20"
		}
	]
}
